# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "randb-dev-tfstate"
    dynamodb_table = ""
    encrypt        = true
    key            = "network/terraform.tfstate"
    region         = "eu-west-2"
  }
}
