name: Artillery Socket.IO Load Test

on:
  push:
    branches:
      - test

jobs:
  artillery:
    runs-on: ubuntu-latest

    # container: artilleryio/artillery:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute load tests
        uses: kenju/github-actions-artillery@master
        with:
          filepath: tests/socket-io.yml

