name: Deploy App test

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - temp
      - develop
  release:
    types: [published]

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read


jobs:
  push_images:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Get space name
        uses: kanga333/variable-mapper@master
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "temp": {"CF_SPACE": "temp"},
              "develop": {"CF_SPACE": "develop"},
              "v?.?.3": {"CF_SPACE": "prod"},
              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
            }

      - name: Setup prod api url
        if:  ${{ github.event_name == 'release' }}
        run: echo "NEXT_PUBLIC_API_URL=https://ellandi-api.london.cloudapps.digital" >> $GITHUB_ENV

      - name: Build, tag, and push ${{ matrix.app }} image

        run: |
          echo ${{ github.ref_name }}
          echo ${{ env.IMAGE_TAG }}
          echo $NEXT_PUBLIC_API_URL
          echo $CF_SPACE
